extern "C" void init_screen_start();
extern "C" void end_screen_start();
extern "C" void limpiar_pantalla_start();
extern "C" void posicionar_cursor_start(int line, int column);
extern "C" void color_fondo_start(int color);
extern "C" void color_texto_start(int color);
extern "C" char caracter_ascii_start(int ascii_value);
extern "C" int valor_ascii_start(char character);
extern "C" char obtener_caracter_start();
extern "C" int obtener_tecla_start();
extern "C" void nueva_linea_start();
extern "C" int aleatorio_start();
extern "C" void inicializar_aleatorio_start();
extern "C" bool tecla_presionada_start();
extern "C" void pausa_start(int milliseconds);
extern "C" int read_int_start();
extern "C" char read_char_start();
extern "C" bool read_bool_start();
extern "C" void print_start(const char *fmt, ...);
